### PR TITLE
Fixed various XSS vulnerabilities

### PR DESCRIPTION
**Pull request by Newman101**
Good afternoon.

Various twigs included major security vulnerabilities attached to |raw filter. Basically, |raw does not escape anything which means that the app is vulnerable to XSS (Cross Site Scripting) injection attacks. Hence, I switched |raw filter to |escape, which improves security and mitigates the XSS vulnerability.

Thank you.

### CODE REVIEW

**Comment by adampiotrowski** [comment]
@Newman101 Hi and thanks for the PR!

I think we should use other than default "html" escaping strategy. According to Twig documentation 

```
The escape filter can also be used in other contexts than HTML thanks to an optional argument which defines the escaping strategy to use:

{{ user.username|e }}
{# is equivalent to #}
{{ user.username|e('html') }}
```
so i think we should use 'js' strategy (haven't tested it yet). I'm curious how it will work with our forms because they're using non-standard JSON.

**Comment by Newman101** [comment]
So would something like this work? 

```
{{ user.username|escape('js') }}
{{ user.username|e('js') }}
```

This escapes only for the JavaScript context.

**Comment by adampiotrowski** [comment]
@Newman101 Yes, but it also messes up rendered JSON in our forms

https://github.com/WellCommerce/WellCommerce/pull/35/files#diff-42faa9a49c1651a6b773fa8e833720a2R6

1) escape('html')
`{
            &quot;sName&quot;: &quot;api_data&quot;,
            &quot;sLabel&quot;: &quot;user.fieldset.api_access&quot;,
            &quot;sClass&quot;: &quot;&quot;,
            &quot;fType&quot;: GFormNestedFieldset,
            &quot;aoFields&quot;: [
                {
                    &quot;sName&quot;: &quot;apiKey&quot;,
                    &quot;sLabel&quot;: &quot;user.label.api_key&quot;,
                    &quot;sClass&quot;: &quot;&quot;,
                    &quot;fType&quot;: GFormTextField,
                    &quot;sValue&quot;: null,
                    &quot;sComment&quot;: &quot;&quot;,
                    &quot;sSize&quot;: &quot;&quot;,
                    &quot;sSuffix&quot;: &quot;&quot;
                }
            ]
        }`

2) escape('js')

`$('#user').GForm(\x7B\x0A\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x22sFormName\x22\x3A\x20\x22user\x22,\x0A\x20\x20\x20\x20\x22sAction\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x22sMethod\x22\x3A\x20\x22POST\x22,\x0A\x20\x20\x20\x20\x22bEnableAjax\x22\x3A\x20true,\x0A\x20\x20\x20\x20\x22iTabs\x22\x3A\x200,\x0A\x20\x20\x20\x20\x22oValues\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x22required_data\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22firstName\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22lastName\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22username\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22email\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22groups\x22\x3A\x20\x5B\x0A\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x22api_data\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22apiKey\x22\x3A\x20null\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x22oErrors\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x22required_data\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22firstName\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22lastName\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22username\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22email\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22groups\x22\x3A\x20\x22\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x22api_data\x22\x3A\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22apiKey\x22\x3A\x20\x22\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x22aoFields\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22required_data\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22General\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormNestedFieldset,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoFields\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22firstName\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22First\x20name\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormTextField,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSize\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSuffix\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoRules\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sType\x3A\x20\x22required\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sErrorMessage\x3A\x20\x22validation.error.not_blank\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22lastName\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22Last\x20name\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormTextField,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSize\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSuffix\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoRules\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sType\x3A\x20\x22required\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sErrorMessage\x3A\x20\x22validation.error.not_blank\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22username\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22Username\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormTextField,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSize\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSuffix\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoRules\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sType\x3A\x20\x22required\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sErrorMessage\x3A\x20\x22validation.error.not_blank\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22email\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22E\x2Dmail\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormTextField,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSize\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSuffix\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoRules\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sType\x3A\x20\x22required\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20sErrorMessage\x3A\x20\x22validation.error.not_blank\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22groups\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22Group\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormMultiSelect,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20\x5B\x0A\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoOptions\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20\x221\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22Administration\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22bAddable\x22\x3A\x20false,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fOnAdd\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sAddItemPrompt\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSelector\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sCssAttribute\x22\x3A\x20\x22\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22api_data\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22user.fieldset.api_access\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormNestedFieldset,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22aoFields\x22\x3A\x20\x5B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7B\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sName\x22\x3A\x20\x22apiKey\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sLabel\x22\x3A\x20\x22user.label.api_key\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sClass\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22fType\x22\x3A\x20GFormTextField,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sValue\x22\x3A\x20null,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sComment\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSize\x22\x3A\x20\x22\x22,\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x22sSuffix\x22\x3A\x20\x22\x22\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5D\x0A\x20\x20\x20\x20\x20\x20\x20\x20\x7D\x0A\x20\x20\x20\x20\x5D\x0A\x7D);`

The output from rendered form JSON should not be escaped.

**Comment by adampiotrowski** [comment]
All vulnerabilities fixed after SensioLabs analyze.

**Pull request closed without merging**
