### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by pborreli**
and using relative symlink asset install instead of hard copy

### CODE REVIEW

**Comment by pborreli** [comment]
done

**Comment by pborreli** [comment]
I had this warning 
```
Class needs to implement '\Symfony\Component\Serializer\Normalizer\NormalizerInterface' for tag 'serializer.normalizer'
Tagged service is missing extends or interface statement

**Comment by adampiotrowski** [comment]
Strange. In such case travis build should fail because container cannot be compiled. Where did you saw this warning?

**Comment by pborreli** [comment]
it's a static analysis from IDE

**Comment by adampiotrowski** [comment]
I'll dig into Symfony internals but the implementation should be fine. It's allowed to separate normalizers and denormalizers as long as they're implementing proper interfaces. Is that analysis from PhpStorm or other IDE?

**Comment by pborreli** [comment]
yes PhpStorm with Symfony2 plugin

**Comment by adampiotrowski** [comment]
@pborreli Ok, i'll check it locally. Thanks for the PR! :+1:

**Comment by pborreli** [comment]
thank you for sharing :+1:

**Comment by pborreli** [comment]
btw, just one question, I installed locally the project, works great, but I can't see the Symfony web debug toolbar, do you see it ?

**Comment by adampiotrowski** [comment]
@pborreli Yes, it depends on which environment are you using. debug_toolbar is enabled by default only for dev environment so app_dev.php. On prod environment (app.php) it won't be visible.

**Comment by pborreli** [comment]
yes i know that :smile: i'm using dev environment app_dev.php but still don't have the wdt js inserted at the end of the html

**Comment by pborreli** [comment]
and see : 
```
app/console config:dump-reference web_profiler --env=dev
# Default configuration for extension with alias: "web_profiler"
web_profiler:
    toolbar:              false
    position:             bottom
    intercept_redirects:  false
    excluded_ajax_paths:  '^/(app(_[\w]+)?\.php/)?_wdt'

**Comment by pborreli** [comment]
and 
```
app/console debug:config web_profiler --env=dev

Current configuration for extension with alias "web_profiler"
=============================================================

web_profiler:
    toolbar: true
    intercept_redirects: false
    position: bottom
    excluded_ajax_paths: '^/(app(_[\w]+)?\.php/)?_wdt'

**Comment by adampiotrowski** [comment]
The config is fine, exactly as on my environment. Did you checked whether the rendered javascripts are visible in page source? No exceptions at the bottom of the page? Do you see any errors in browser dev console?

**Comment by pborreli** [comment]
no js in html, no exceptions, nothing in console except a warning from chrome about less.js xhr

**Comment by pborreli** [comment]
i even tried to put the content of app_dev.php inside app.php to be sure it was not nginx pointing only to app.php, no luck.

**Comment by adampiotrowski** [comment]
And there's no profiler no matter if front or admin area? What browser, Chrome? 
Could you pls check also nginx error logs and app/logs/dev for any trace?
Can you access the profiler directly from browser? 
http://wellcommerce.dev/app_dev.php/_profiler/search?limit=10

**Comment by pborreli** [comment]
no profiler in front or admin
chrome
i don't see any error in nginx / php / symfony logs 
I can access _profiler but it stays always empty
btw I have other Symfony projects with same docker config and they work just fine
thx for the help,

**Comment by pborreli** [comment]
found out ! 
had to specify as I use docker ..
developer_mode.ip: 192.168.99.1

**Comment by adampiotrowski** [comment]
@pborreli Damn! I forgot that i've added a restriction once

**parameters.yml:**
`developer_mode.ip: 127.0.0.1`

**framework.ml (in AppBundle):**
```
    profiler:
        matcher: { ip: "%developer_mode.ip%" }
```

Thanks for doing the investigation Sir :). I'll note somewhere to add additional configuration instructions for Docker.

**Comment by adampiotrowski** [comment]
@pborreli Btw, i didn't even tested on Docker. Everything is working fine?

**Comment by pborreli** [comment]
yes, PHPUnit is running atm, no error so far ..

**Comment by adampiotrowski** [comment]
That's awesome! :)

**Pull request merged**
